### ISSUE TITLE
How to perform a prior scan?

### ISSUE THREAD

**Issue by fzeiser** [anderkve/gambit_np#2]
How can I perform a prior scan? I though I could simply use `random` as a scanner, to *randomly* go through the priors distribution specified in the model. If there is a way to avoid calculating the likelihood it'd be computationally cheaper, but that's not a major problem right now.

So I tried this and I'm confused by the output of  `random` . I ran with the attached yaml file, here a short description
[NuclearBit_162Dy_22.yaml.txt](https://github.com/anderkve/gambit_np/files/5400856/NuclearBit_162Dy_22.yaml.txt)

```
Parameters:

  GSFModel20:
    gsf_p1:
      prior_type: flat
      range: [11, 13]
    gsf_p2:
      prior_type: flat
      range: [100, 400]
    gsf_p3:
      prior_type: flat
      range: [2., 5]
[...]

  scanners:

    random:
      plugin: random
      point_number: 10000
      like: LogLike
```
I ran it with `mpi -np 8`.
So I would have expected that the points sampled for `gsf_p1` are flat between 11 and 13. However, 
- sample 1- 6999 are 11.0 
- 7000 - 7999 are between  11 and 13
- 8000 - 14999 are 11.0
- 15000 - 15999 are between  11 and 13
- ... (some other behavior towards the end)

This is unexpected: I get ~1/8th of the samples at 11.0?

Similar behavior for the other parameters.
